---
name: databaseconnectors
---
Injector:
  MySQLPDODatabase:
    class: 'MySQLDatabase'
    properties:
      connector: %$PDOConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLDatabase:
    class: 'MySQLDatabase'
    properties:
      connector: %$MySQLiConnector
      schemaManager: %$MySQLSchemaManager
      queryBuilder: %$MySQLQueryBuilder
  MySQLiConnector:
    class: 'MySQLiConnector'
    type: prototype
  PDOConnector:
    class: 'PDOConnector'
    type: prototype
  # These are added from the silverstripe-327 module so that module doesn't need to be installed. MG 2016-03-16
  Int:
    class: DBInt
  Float:
    class: DBFloat
